name: Ashraf 

on:
   push:
      branches : ["branch1"]
   pull_request:
      branches : ["branch2"]
jobs:
  build : 
    runs-on: ubuntu-latest
    container: python :3.9-slim 
    steps: 
      - name: Chekout
        uses: actions/checkout@v3

      - name: Install depedencies 
        run: 
         python3.8 -m pip install --upgrade pip
         pip3 install -r requirements.txt
      - name: Lint with flake8
        run: 
         flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
  